/*******************************************************************************
*
*  (C) COPYRIGHT AUTHORS, 2016
*
*  TITLE:       UNBCL.H
*
*  VERSION:     2.10
*
*  DATE:        14 Apr 2016
*
*  UNBCL forwarded import.
*
* THIS CODE AND INFORMATION IS PROVIDED "AS IS" WITHOUT WARRANTY OF
* ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED
* TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A
* PARTICULAR PURPOSE.
*
*******************************************************************************/

#pragma once

//no it wasn't created manually

//Windows 8.1
#pragma comment(linker, " /EXPORT:??0?$IEnumerator@PEAVString@UnBCL@@@UnBCL@@QEAA@XZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??0?$IEnumerator@PEAVString@UnBCL@@@UnBCL@@QEAA@XZ")
#pragma comment(linker, " /EXPORT:??0?$ICollection@PEAVString@UnBCL@@@UnBCL@@QEAA@XZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??0?$ICollection@PEAVString@UnBCL@@@UnBCL@@QEAA@XZ")
#pragma comment(linker, " /EXPORT:??0ISerializable@UnBCL@@QEAA@XZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??0ISerializable@UnBCL@@QEAA@XZ")
#pragma comment(linker, " /EXPORT:??0?$IList@E@UnBCL@@QEAA@XZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??0?$IList@E@UnBCL@@QEAA@XZ")
#pragma comment(linker, " /EXPORT:??0?$ICollection@E@UnBCL@@QEAA@XZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??0?$ICollection@E@UnBCL@@QEAA@XZ")

//Windows 10 + common
#pragma comment(linker, " /EXPORT:??0?$Array@E@UnBCL@@QEAA@PEBU?$ICollection@E@1@@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??0?$Array@E@UnBCL@@QEAA@PEBU?$ICollection@E@1@@Z")
#pragma comment(linker, " /EXPORT:??0?$ArrayList@PEAVString@UnBCL@@@UnBCL@@QEAA@XZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??0?$ArrayList@PEAVString@UnBCL@@@UnBCL@@QEAA@XZ")
#pragma comment(linker, " /EXPORT:??0?$Hashtable@PEAVString@UnBCL@@PEAV12@@UnBCL@@QEAA@HH@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??0?$Hashtable@PEAVString@UnBCL@@PEAV12@@UnBCL@@QEAA@HH@Z")
#pragma comment(linker, " /EXPORT:??0?$SmartPtr@V?$Array@PEAVString@UnBCL@@@UnBCL@@@UnBCL@@QEAA@PEAV?$Array@PEAVString@UnBCL@@@1@@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??0?$SmartPtr@V?$Array@PEAVString@UnBCL@@@UnBCL@@@UnBCL@@QEAA@PEAV?$Array@PEAVString@UnBCL@@@1@@Z")
#pragma comment(linker, " /EXPORT:??0?$SmartPtr@V?$ArrayList@PEAVString@UnBCL@@@UnBCL@@@UnBCL@@QEAA@PEAV?$ArrayList@PEAVString@UnBCL@@@1@@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??0?$SmartPtr@V?$ArrayList@PEAVString@UnBCL@@@UnBCL@@@UnBCL@@QEAA@PEAV?$ArrayList@PEAVString@UnBCL@@@1@@Z")
#pragma comment(linker, " /EXPORT:??0?$SmartPtr@VString@UnBCL@@@UnBCL@@QEAA@PEAVString@1@@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??0?$SmartPtr@VString@UnBCL@@@UnBCL@@QEAA@PEAVString@1@@Z")
#pragma comment(linker, " /EXPORT:??0?$SmartPtr@VString@UnBCL@@@UnBCL@@QEAA@XZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??0?$SmartPtr@VString@UnBCL@@@UnBCL@@QEAA@XZ")
#pragma comment(linker, " /EXPORT:??0ArgumentException@UnBCL@@QEAA@PEBG@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??0ArgumentException@UnBCL@@QEAA@PEBG@Z")
#pragma comment(linker, " /EXPORT:??0ArgumentNullException@UnBCL@@QEAA@PEBG@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??0ArgumentNullException@UnBCL@@QEAA@PEBG@Z")
#pragma comment(linker, " /EXPORT:??0ArgumentOutOfRangeException@UnBCL@@QEAA@PEBG@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??0ArgumentOutOfRangeException@UnBCL@@QEAA@PEBG@Z")
#pragma comment(linker, " /EXPORT:??0Exception@UnBCL@@QEAA@PEBG@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??0Exception@UnBCL@@QEAA@PEBG@Z")
#pragma comment(linker, " /EXPORT:??0InvalidCastException@UnBCL@@QEAA@XZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??0InvalidCastException@UnBCL@@QEAA@XZ")
#pragma comment(linker, " /EXPORT:??0InvalidOperationException@UnBCL@@QEAA@PEBG@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??0InvalidOperationException@UnBCL@@QEAA@PEBG@Z")
#pragma comment(linker, " /EXPORT:??0InvalidOperationException@UnBCL@@QEAA@PEBVString@1@@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??0InvalidOperationException@UnBCL@@QEAA@PEBVString@1@@Z")
#pragma comment(linker, " /EXPORT:??0InvalidOperationException@UnBCL@@QEAA@PEBVString@1@PEAVException@1@@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??0InvalidOperationException@UnBCL@@QEAA@PEBVString@1@PEAVException@1@@Z")
#pragma comment(linker, " /EXPORT:??0MultiSz@UnBCL@@QEAA@XZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??0MultiSz@UnBCL@@QEAA@XZ")
#pragma comment(linker, " /EXPORT:??0MutableString@UnBCL@@QEAA@PEBG@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??0MutableString@UnBCL@@QEAA@PEBG@Z")
#pragma comment(linker, " /EXPORT:??0MutableString@UnBCL@@QEAA@PEBGHH@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??0MutableString@UnBCL@@QEAA@PEBGHH@Z")
#pragma comment(linker, " /EXPORT:??0MutableString@UnBCL@@QEAA@XZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??0MutableString@UnBCL@@QEAA@XZ")
#pragma comment(linker, " /EXPORT:??0NotSupportedException@UnBCL@@QEAA@PEBG@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??0NotSupportedException@UnBCL@@QEAA@PEBG@Z")
#pragma comment(linker, " /EXPORT:??0Object@UnBCL@@QEAA@AEBV01@@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??0Object@UnBCL@@QEAA@AEBV01@@Z")
#pragma comment(linker, " /EXPORT:??0Object@UnBCL@@QEAA@XZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??0Object@UnBCL@@QEAA@XZ")
#pragma comment(linker, " /EXPORT:??0String@UnBCL@@QEAA@AEBV01@@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??0String@UnBCL@@QEAA@AEBV01@@Z")
#pragma comment(linker, " /EXPORT:??0String@UnBCL@@QEAA@PEBG@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??0String@UnBCL@@QEAA@PEBG@Z")
#pragma comment(linker, " /EXPORT:??0String@UnBCL@@QEAA@PEBGHH@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??0String@UnBCL@@QEAA@PEBGHH@Z")
#pragma comment(linker, " /EXPORT:??0StringBuilder@UnBCL@@QEAA@XZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??0StringBuilder@UnBCL@@QEAA@XZ")
#pragma comment(linker, " /EXPORT:??0XmlDocument@UnBCL@@QEAA@XZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??0XmlDocument@UnBCL@@QEAA@XZ")
#pragma comment(linker, " /EXPORT:??1?$ICollection@E@UnBCL@@UEAA@XZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??1?$ICollection@E@UnBCL@@UEAA@XZ")
#pragma comment(linker, " /EXPORT:??1?$IList@E@UnBCL@@UEAA@XZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??1?$IList@E@UnBCL@@UEAA@XZ")
#pragma comment(linker, " /EXPORT:??1?$SmartPtr@V?$Array@PEAVString@UnBCL@@@UnBCL@@@UnBCL@@UEAA@XZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??1?$SmartPtr@V?$Array@PEAVString@UnBCL@@@UnBCL@@@UnBCL@@UEAA@XZ")
#pragma comment(linker, " /EXPORT:??1?$SmartPtr@V?$ArrayList@PEAVString@UnBCL@@@UnBCL@@@UnBCL@@UEAA@XZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??1?$SmartPtr@V?$ArrayList@PEAVString@UnBCL@@@UnBCL@@@UnBCL@@UEAA@XZ")
#pragma comment(linker, " /EXPORT:??1?$SmartPtr@VString@UnBCL@@@UnBCL@@UEAA@XZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??1?$SmartPtr@VString@UnBCL@@@UnBCL@@UEAA@XZ")
#pragma comment(linker, " /EXPORT:??1ArgumentException@UnBCL@@UEAA@XZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??1ArgumentException@UnBCL@@UEAA@XZ")
#pragma comment(linker, " /EXPORT:??1ArgumentNullException@UnBCL@@UEAA@XZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??1ArgumentNullException@UnBCL@@UEAA@XZ")
#pragma comment(linker, " /EXPORT:??1ArgumentOutOfRangeException@UnBCL@@UEAA@XZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??1ArgumentOutOfRangeException@UnBCL@@UEAA@XZ")
#pragma comment(linker, " /EXPORT:??1Exception@UnBCL@@UEAA@XZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??1Exception@UnBCL@@UEAA@XZ")
#pragma comment(linker, " /EXPORT:??1InvalidCastException@UnBCL@@UEAA@XZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??1InvalidCastException@UnBCL@@UEAA@XZ")
#pragma comment(linker, " /EXPORT:??1InvalidOperationException@UnBCL@@UEAA@XZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??1InvalidOperationException@UnBCL@@UEAA@XZ")
#pragma comment(linker, " /EXPORT:??1ISerializable@UnBCL@@UEAA@XZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??1ISerializable@UnBCL@@UEAA@XZ")
#pragma comment(linker, " /EXPORT:??1MutableString@UnBCL@@UEAA@XZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??1MutableString@UnBCL@@UEAA@XZ")
#pragma comment(linker, " /EXPORT:??1NotSupportedException@UnBCL@@UEAA@XZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??1NotSupportedException@UnBCL@@UEAA@XZ")
#pragma comment(linker, " /EXPORT:??1Object@UnBCL@@UEAA@XZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??1Object@UnBCL@@UEAA@XZ")
#pragma comment(linker, " /EXPORT:??1String@UnBCL@@UEAA@XZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??1String@UnBCL@@UEAA@XZ")
#pragma comment(linker, " /EXPORT:??1StringBuilder@UnBCL@@UEAA@XZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??1StringBuilder@UnBCL@@UEAA@XZ")
#pragma comment(linker, " /EXPORT:??1XmlDocument@UnBCL@@UEAA@XZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??1XmlDocument@UnBCL@@UEAA@XZ")
#pragma comment(linker, " /EXPORT:??2Object@UnBCL@@SAPEAX_K@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??2Object@UnBCL@@SAPEAX_K@Z")
#pragma comment(linker, " /EXPORT:??2Object@UnBCL@@SAPEAX_KI@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??2Object@UnBCL@@SAPEAX_KI@Z")
#pragma comment(linker, " /EXPORT:??3Object@UnBCL@@SAXPEAX@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??3Object@UnBCL@@SAXPEAX@Z")
#pragma comment(linker, " /EXPORT:??4?$SmartPtr@VString@UnBCL@@@UnBCL@@QEAAAEAV01@AEBV01@@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??4?$SmartPtr@VString@UnBCL@@@UnBCL@@QEAAAEAV01@AEBV01@@Z")
#pragma comment(linker, " /EXPORT:??5SerializationStream@UnBCL@@QEAAAEAV01@AEAH@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??5SerializationStream@UnBCL@@QEAAAEAV01@AEAH@Z")
#pragma comment(linker, " /EXPORT:??5SerializationStream@UnBCL@@QEAAAEAV01@AEAK@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??5SerializationStream@UnBCL@@QEAAAEAV01@AEAK@Z")
#pragma comment(linker, " /EXPORT:??5SerializationStream@UnBCL@@QEAAAEAV01@AEAPEAUISerializable@1@@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??5SerializationStream@UnBCL@@QEAAAEAV01@AEAPEAUISerializable@1@@Z")
#pragma comment(linker, " /EXPORT:??5SerializationStream@UnBCL@@QEAAAEAV01@AEAPEAVString@1@@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??5SerializationStream@UnBCL@@QEAAAEAV01@AEAPEAVString@1@@Z")
#pragma comment(linker, " /EXPORT:??6SerializationStream@UnBCL@@QEAAAEAV01@H@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??6SerializationStream@UnBCL@@QEAAAEAV01@H@Z")
#pragma comment(linker, " /EXPORT:??6SerializationStream@UnBCL@@QEAAAEAV01@K@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??6SerializationStream@UnBCL@@QEAAAEAV01@K@Z")
#pragma comment(linker, " /EXPORT:??6SerializationStream@UnBCL@@QEAAAEAV01@PEBUISerializable@1@@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??6SerializationStream@UnBCL@@QEAAAEAV01@PEBUISerializable@1@@Z")
#pragma comment(linker, " /EXPORT:??6SerializationStream@UnBCL@@QEAAAEAV01@PEBVString@1@@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??6SerializationStream@UnBCL@@QEAAAEAV01@PEBVString@1@@Z")
#pragma comment(linker, " /EXPORT:??_D?$Array@E@UnBCL@@QEAAXXZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??_D?$Array@E@UnBCL@@QEAAXXZ")
#pragma comment(linker, " /EXPORT:??_D?$ArrayList@PEAVString@UnBCL@@@UnBCL@@QEAAXXZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??_D?$ArrayList@PEAVString@UnBCL@@@UnBCL@@QEAAXXZ")
#pragma comment(linker, " /EXPORT:??_D?$Hashtable@PEAVString@UnBCL@@PEAV12@@UnBCL@@QEAAXXZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??_D?$Hashtable@PEAVString@UnBCL@@PEAV12@@UnBCL@@QEAAXXZ")
#pragma comment(linker, " /EXPORT:??_DMultiSz@UnBCL@@QEAAXXZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??_DMultiSz@UnBCL@@QEAAXXZ")
#pragma comment(linker, " /EXPORT:??C?$SmartPtr@V?$Array@PEAVString@UnBCL@@@UnBCL@@@UnBCL@@QEBAPEAV?$Array@PEAVString@UnBCL@@@1@XZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??C?$SmartPtr@V?$Array@PEAVString@UnBCL@@@UnBCL@@@UnBCL@@QEBAPEAV?$Array@PEAVString@UnBCL@@@1@XZ")
#pragma comment(linker, " /EXPORT:??C?$SmartPtr@V?$ArrayList@PEAVString@UnBCL@@@UnBCL@@@UnBCL@@QEBAPEAV?$ArrayList@PEAVString@UnBCL@@@1@XZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??C?$SmartPtr@V?$ArrayList@PEAVString@UnBCL@@@UnBCL@@@UnBCL@@QEBAPEAV?$ArrayList@PEAVString@UnBCL@@@1@XZ")
#pragma comment(linker, " /EXPORT:??C?$SmartPtr@VString@UnBCL@@@UnBCL@@QEBAPEAVString@1@XZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??C?$SmartPtr@VString@UnBCL@@@UnBCL@@QEBAPEAVString@1@XZ")
#pragma comment(linker, " /EXPORT:??D?$SmartPtr@VString@UnBCL@@@UnBCL@@QEBAAEAVString@1@XZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.??D?$SmartPtr@VString@UnBCL@@@UnBCL@@QEBAAEAVString@1@XZ")
#pragma comment(linker, " /EXPORT:?Add@MultiSz@UnBCL@@QEAAXPEBG@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?Add@MultiSz@UnBCL@@QEAAXPEBG@Z")
#pragma comment(linker, " /EXPORT:?AddRef@Object@UnBCL@@QEAAXXZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?AddRef@Object@UnBCL@@QEAAXXZ")
#pragma comment(linker, " /EXPORT:?AddStackTrace@Exception@UnBCL@@QEAAXPEBD@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?AddStackTrace@Exception@UnBCL@@QEAAXPEBD@Z")
#pragma comment(linker, " /EXPORT:?Append@MutableString@UnBCL@@QEAAXPEBG@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?Append@MutableString@UnBCL@@QEAAXPEBG@Z")
#pragma comment(linker, " /EXPORT:?Append@StringBuilder@UnBCL@@QEAAPEAV12@PEBG@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?Append@StringBuilder@UnBCL@@QEAAPEAV12@PEBG@Z")
#pragma comment(linker, " /EXPORT:?Append@StringBuilder@UnBCL@@QEAAPEAV12@PEBVString@2@@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?Append@StringBuilder@UnBCL@@QEAAPEAV12@PEBVString@2@@Z")
#pragma comment(linker, " /EXPORT:?Assign@?$SmartPtr@VString@UnBCL@@@UnBCL@@AEAAXPEAVString@2@@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?Assign@?$SmartPtr@VString@UnBCL@@@UnBCL@@AEAAXPEAVString@2@@Z")
#pragma comment(linker, " /EXPORT:?CanRegister@SerializationStream@UnBCL@@SAHXZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?CanRegister@SerializationStream@UnBCL@@SAHXZ")
#pragma comment(linker, " /EXPORT:?Clone@?$Array@E@UnBCL@@UEBAPEAVObject@2@XZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?Clone@?$Array@E@UnBCL@@UEBAPEAVObject@2@XZ")
#pragma comment(linker, " /EXPORT:?Clone@?$ArrayList@PEAVString@UnBCL@@@UnBCL@@UEBAPEAVObject@2@XZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?Clone@?$ArrayList@PEAVString@UnBCL@@@UnBCL@@UEBAPEAVObject@2@XZ")
#pragma comment(linker, " /EXPORT:?Clone@Object@UnBCL@@UEBAPEAV12@XZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?Clone@Object@UnBCL@@UEBAPEAV12@XZ")
#pragma comment(linker, " /EXPORT:?Clone@String@UnBCL@@UEBAPEAVObject@2@XZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?Clone@String@UnBCL@@UEBAPEAVObject@2@XZ")
#pragma comment(linker, " /EXPORT:?CompareTo@Object@UnBCL@@UEBAHPEBV12@@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?CompareTo@Object@UnBCL@@UEBAHPEBV12@@Z")
#pragma comment(linker, " /EXPORT:?CompareTo@String@UnBCL@@QEBAHPEBG@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?CompareTo@String@UnBCL@@QEBAHPEBG@Z")
#pragma comment(linker, " /EXPORT:?CompareTo@String@UnBCL@@QEBAHPEBGH@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?CompareTo@String@UnBCL@@QEBAHPEBGH@Z")
#pragma comment(linker, " /EXPORT:?CompareTo@String@UnBCL@@UEBAHPEBVObject@2@@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?CompareTo@String@UnBCL@@UEBAHPEBVObject@2@@Z")
#pragma comment(linker, " /EXPORT:?Concat@String@UnBCL@@SAPEAV12@PEBG0@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?Concat@String@UnBCL@@SAPEAV12@PEBG0@Z")
#pragma comment(linker, " /EXPORT:?Concat@String@UnBCL@@SAPEAV12@PEBG@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?Concat@String@UnBCL@@SAPEAV12@PEBG@Z")
#pragma comment(linker, " /EXPORT:?DecRef@Object@UnBCL@@QEAAHXZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?DecRef@Object@UnBCL@@QEAAHXZ")
#pragma comment(linker, " /EXPORT:?Delete@Directory@UnBCL@@SAXPEBVString@2@H@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?Delete@Directory@UnBCL@@SAXPEBVString@2@H@Z")
#pragma comment(linker, " /EXPORT:?Delete@File@UnBCL@@SAXPEBVString@2@@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?Delete@File@UnBCL@@SAXPEBVString@2@@Z")
#pragma comment(linker, " /EXPORT:?EndsWith@String@UnBCL@@QEBAHPEBGH@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?EndsWith@String@UnBCL@@QEBAHPEBGH@Z")
#pragma comment(linker, " /EXPORT:?EnqueueSbRegistration@SbRegistrationList@UnBCL@@SAXPEBDHPEAUHINSTANCE__@@PEAUIInstanceFactory@2@@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?EnqueueSbRegistration@SbRegistrationList@UnBCL@@SAXPEBDHPEAUHINSTANCE__@@PEAUIInstanceFactory@2@@Z")
#pragma comment(linker, " /EXPORT:?Equals@?$Array@E@UnBCL@@UEBAHPEBVObject@2@@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?Equals@?$Array@E@UnBCL@@UEBAHPEBVObject@2@@Z")
#pragma comment(linker, " /EXPORT:?Equals@?$ArrayList@PEAVString@UnBCL@@@UnBCL@@UEBAHPEBVObject@2@@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?Equals@?$ArrayList@PEAVString@UnBCL@@@UnBCL@@UEBAHPEBVObject@2@@Z")
#pragma comment(linker, " /EXPORT:?Equals@Object@UnBCL@@UEBAHPEBV12@@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?Equals@Object@UnBCL@@UEBAHPEBV12@@Z")
#pragma comment(linker, " /EXPORT:?Equals@String@UnBCL@@UEBAHPEBVObject@2@@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?Equals@String@UnBCL@@UEBAHPEBVObject@2@@Z")
#pragma comment(linker, " /EXPORT:?Exists@Directory@UnBCL@@SAHPEBVString@2@@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?Exists@Directory@UnBCL@@SAHPEBVString@2@@Z")
#pragma comment(linker, " /EXPORT:?Exists@File@UnBCL@@SAHPEBVString@2@@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?Exists@File@UnBCL@@SAHPEBVString@2@@Z")
#pragma comment(linker, " /EXPORT:?Format@String@UnBCL@@SAPEAV12@PEBGZZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?Format@String@UnBCL@@SAPEAV12@PEBGZZ")
#pragma comment(linker, " /EXPORT:?FromASCII@String@UnBCL@@SAPEAV12@PEBD@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?FromASCII@String@UnBCL@@SAPEAV12@PEBD@Z")
#pragma comment(linker, " /EXPORT:?get_Attributes@XmlNode@UnBCL@@QEAAPEAVXmlAttributeCollection@2@XZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?get_Attributes@XmlNode@UnBCL@@QEAAPEAVXmlAttributeCollection@2@XZ")
#pragma comment(linker, " /EXPORT:?get_Buffer@MultiSz@UnBCL@@QEBAPEBGXZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?get_Buffer@MultiSz@UnBCL@@QEBAPEBGXZ")
#pragma comment(linker, " /EXPORT:?get_Chars@String@UnBCL@@QEBAAEBGH@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?get_Chars@String@UnBCL@@QEBAAEBGH@Z")
#pragma comment(linker, " /EXPORT:?get_ChildNodes@XmlNode@UnBCL@@QEAAPEAVXmlNodeList@2@XZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?get_ChildNodes@XmlNode@UnBCL@@QEAAPEAVXmlNodeList@2@XZ")
#pragma comment(linker, " /EXPORT:?get_Count@XmlAttributeCollection@UnBCL@@QEAAHXZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?get_Count@XmlAttributeCollection@UnBCL@@QEAAHXZ")
#pragma comment(linker, " /EXPORT:?get_Count@XmlNodeList@UnBCL@@QEAAHXZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?get_Count@XmlNodeList@UnBCL@@QEAAHXZ")
#pragma comment(linker, " /EXPORT:?get_CString@String@UnBCL@@QEBAPEBGXZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?get_CString@String@UnBCL@@QEBAPEBGXZ")
#pragma comment(linker, " /EXPORT:?get_HResult@Exception@UnBCL@@UEBAJXZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?get_HResult@Exception@UnBCL@@UEBAJXZ")
#pragma comment(linker, " /EXPORT:?get_InnerException@Exception@UnBCL@@UEBAPEBV12@XZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?get_InnerException@Exception@UnBCL@@UEBAPEBV12@XZ")
#pragma comment(linker, " /EXPORT:?get_Item@XmlAttributeCollection@UnBCL@@QEAAPEAVXmlAttribute@2@PEAVString@2@@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?get_Item@XmlAttributeCollection@UnBCL@@QEAAPEAVXmlAttribute@2@PEAVString@2@@Z")
#pragma comment(linker, " /EXPORT:?get_Item@XmlNodeList@UnBCL@@QEAAPEAVXmlNode@2@H@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?get_Item@XmlNodeList@UnBCL@@QEAAPEAVXmlNode@2@H@Z")
#pragma comment(linker, " /EXPORT:?get_Length@String@UnBCL@@QEBAHXZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?get_Length@String@UnBCL@@QEBAHXZ")
#pragma comment(linker, " /EXPORT:?get_Message@Exception@UnBCL@@UEBAPEBVString@2@XZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?get_Message@Exception@UnBCL@@UEBAPEBVString@2@XZ")
#pragma comment(linker, " /EXPORT:?get_Name@XmlNode@UnBCL@@QEAAPEAVString@2@XZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?get_Name@XmlNode@UnBCL@@QEAAPEAVString@2@XZ")
#pragma comment(linker, " /EXPORT:?get_P@?$SmartPtr@V?$ArrayList@PEAVString@UnBCL@@@UnBCL@@@UnBCL@@QEBAPEAV?$ArrayList@PEAVString@UnBCL@@@2@XZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?get_P@?$SmartPtr@V?$ArrayList@PEAVString@UnBCL@@@UnBCL@@@UnBCL@@QEBAPEAV?$ArrayList@PEAVString@UnBCL@@@2@XZ")
#pragma comment(linker, " /EXPORT:?get_P@?$SmartPtr@VString@UnBCL@@@UnBCL@@QEBAPEAVString@2@XZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?get_P@?$SmartPtr@VString@UnBCL@@@UnBCL@@QEBAPEAVString@2@XZ")
#pragma comment(linker, " /EXPORT:?get_Source@Exception@UnBCL@@UEBAPEBVString@2@XZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?get_Source@Exception@UnBCL@@UEBAPEBVString@2@XZ")
#pragma comment(linker, " /EXPORT:?get_Value@XmlNode@UnBCL@@QEAAPEAVString@2@XZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?get_Value@XmlNode@UnBCL@@QEAAPEAVString@2@XZ")
#pragma comment(linker, " /EXPORT:?get_Win32ErrorCode@Win32Exception@UnBCL@@QEBAKXZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?get_Win32ErrorCode@Win32Exception@UnBCL@@QEBAKXZ")
#pragma comment(linker, " /EXPORT:?GetBaseException@Exception@UnBCL@@UEBAPEBV12@XZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?GetBaseException@Exception@UnBCL@@UEBAPEBV12@XZ")
#pragma comment(linker, " /EXPORT:?GetCallingModule@SerializationStream@UnBCL@@SAPEAUHINSTANCE__@@XZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?GetCallingModule@SerializationStream@UnBCL@@SAPEAUHINSTANCE__@@XZ")
#pragma comment(linker, " /EXPORT:?GetFiles@Directory@UnBCL@@SAPEAV?$Array@PEAVString@UnBCL@@@2@PEBVString@2@0H@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?GetFiles@Directory@UnBCL@@SAPEAV?$Array@PEAVString@UnBCL@@@2@PEBVString@2@0H@Z")
#pragma comment(linker, " /EXPORT:?GetHashCode@Object@UnBCL@@UEBAHXZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?GetHashCode@Object@UnBCL@@UEBAHXZ")
#pragma comment(linker, " /EXPORT:?GetHashCode@String@UnBCL@@UEBAHXZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?GetHashCode@String@UnBCL@@UEBAHXZ")
#pragma comment(linker, " /EXPORT:?GetObjectID@Object@UnBCL@@UEBAIXZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?GetObjectID@Object@UnBCL@@UEBAIXZ")
#pragma comment(linker, " /EXPORT:?GetStackTrace@Exception@UnBCL@@QEBAPEAVString@2@XZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?GetStackTrace@Exception@UnBCL@@QEBAPEAVString@2@XZ")
#pragma comment(linker, " /EXPORT:?GetType@Object@UnBCL@@UEBAPEAVType@2@XZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?GetType@Object@UnBCL@@UEBAPEAVType@2@XZ")
#pragma comment(linker, " /EXPORT:?IndexOf@String@UnBCL@@QEBAHG@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?IndexOf@String@UnBCL@@QEBAHG@Z")
#pragma comment(linker, " /EXPORT:?IndexOf@String@UnBCL@@QEBAHPEBGH@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?IndexOf@String@UnBCL@@QEBAHPEBGH@Z")
#pragma comment(linker, " /EXPORT:?LastIndexOf@String@UnBCL@@QEBAHG@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?LastIndexOf@String@UnBCL@@QEBAHG@Z")
#pragma comment(linker, " /EXPORT:?Load@XmlDocument@UnBCL@@QEAAXPEAVString@2@@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?Load@XmlDocument@UnBCL@@QEAAXPEAVString@2@@Z")
#pragma comment(linker, " /EXPORT:?MakeLower@MutableString@UnBCL@@QEAAXXZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?MakeLower@MutableString@UnBCL@@QEAAXXZ")
#pragma comment(linker, " /EXPORT:?MakeTrim@MutableString@UnBCL@@QEAAXPEBG@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?MakeTrim@MutableString@UnBCL@@QEAAXPEBG@Z")
#pragma comment(linker, " /EXPORT:?MemAllocFailed@Allocator@UnBCL@@SAHXZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?MemAllocFailed@Allocator@UnBCL@@SAHXZ")
#pragma comment(linker, " /EXPORT:?ReadBytes@SerializationStream@UnBCL@@QEAAXPEAEH@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?ReadBytes@SerializationStream@UnBCL@@QEAAXPEAEH@Z")
#pragma comment(linker, " /EXPORT:?RegisterType@SerializationStream@UnBCL@@SAXPEBVString@2@HPEAUHINSTANCE__@@PEAUIInstanceFactory@2@@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?RegisterType@SerializationStream@UnBCL@@SAXPEBVString@2@HPEAUHINSTANCE__@@PEAUIInstanceFactory@2@@Z")
#pragma comment(linker, " /EXPORT:?SanitizeTypeName@SerializationStream@UnBCL@@SAPEAVString@2@AEBV32@@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?SanitizeTypeName@SerializationStream@UnBCL@@SAPEAVString@2@AEBV32@@Z")
#pragma comment(linker, " /EXPORT:?SelectNodes@XmlNode@UnBCL@@QEAAPEAVXmlNodeList@2@PEAVString@2@@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?SelectNodes@XmlNode@UnBCL@@QEAAPEAVXmlNodeList@2@PEAVString@2@@Z")
#pragma comment(linker, " /EXPORT:?SelectSingleNode@XmlNode@UnBCL@@QEAAPEAV12@PEAVString@2@@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?SelectSingleNode@XmlNode@UnBCL@@QEAAPEAV12@PEAVString@2@@Z")
#pragma comment(linker, " /EXPORT:?set_HResult@Exception@UnBCL@@MEAAXJ@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?set_HResult@Exception@UnBCL@@MEAAXJ@Z")
#pragma comment(linker, " /EXPORT:?set_Source@Exception@UnBCL@@UEAAXPEBVString@2@@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?set_Source@Exception@UnBCL@@UEAAXPEBVString@2@@Z")
#pragma comment(linker, " /EXPORT:?SetLiteralStorage@_@UnBCL@@YAXPEAPEBVString@2@PEBG@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?SetLiteralStorage@_@UnBCL@@YAXPEAPEBVString@2@PEBG@Z")
#pragma comment(linker, " /EXPORT:?SetMessage@Exception@UnBCL@@MEAAXPEAVString@2@@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?SetMessage@Exception@UnBCL@@MEAAXPEAVString@2@@Z")
#pragma comment(linker, " /EXPORT:?StartsWith@String@UnBCL@@QEBAHPEBGH@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?StartsWith@String@UnBCL@@QEBAHPEBGH@Z")
#pragma comment(linker, " /EXPORT:?Steal@?$SmartPtr@VString@UnBCL@@@UnBCL@@QEAAPEAVString@2@XZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?Steal@?$SmartPtr@VString@UnBCL@@@UnBCL@@QEAAPEAVString@2@XZ")
#pragma comment(linker, " /EXPORT:?Substring@String@UnBCL@@QEBAPEAV12@H@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?Substring@String@UnBCL@@QEBAPEAV12@H@Z")
#pragma comment(linker, " /EXPORT:?Substring@String@UnBCL@@QEBAPEAV12@HH@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?Substring@String@UnBCL@@QEBAPEAV12@HH@Z")
#pragma comment(linker, " /EXPORT:?ToString@Exception@UnBCL@@UEBAPEAVString@2@XZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?ToString@Exception@UnBCL@@UEBAPEAVString@2@XZ")
#pragma comment(linker, " /EXPORT:?ToString@Object@UnBCL@@UEBAPEAVString@2@XZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?ToString@Object@UnBCL@@UEBAPEAVString@2@XZ")
#pragma comment(linker, " /EXPORT:?ToString@String@UnBCL@@UEBAPEAV12@XZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?ToString@String@UnBCL@@UEBAPEAV12@XZ")
#pragma comment(linker, " /EXPORT:?ToString@StringBuilder@UnBCL@@UEBAPEAVString@2@XZ=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?ToString@StringBuilder@UnBCL@@UEBAPEAVString@2@XZ")
#pragma comment(linker, " /EXPORT:?UnregisterType@SerializationStream@UnBCL@@SAXPEBVString@2@HPEAUHINSTANCE__@@@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?UnregisterType@SerializationStream@UnBCL@@SAXPEBVString@2@HPEAUHINSTANCE__@@@Z")
#pragma comment(linker, " /EXPORT:?WriteBytes@SerializationStream@UnBCL@@QEAAXPEBEH@Z=\\\\?\\globalroot\\systemroot\\system32\\sysprep\\unbcl.?WriteBytes@SerializationStream@UnBCL@@QEAAXPEBEH@Z")
