name: Build UACME

on:
  push:
    branches: [ "**" ] # 任何分支有 Push 都会触发
  pull_request:
    branches: [ "**" ]
  workflow_dispatch: # 支持手动点击按钮触发

env:
  ACTIONS_RUNNER_FORCE_NODE24: "true"

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4.2.2 # 默认自动拉取当前触发工作流的分支

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Build x64 Release
      run: |
        msbuild Source\uacme.sln /m /v:minimal /p:Configuration=Release /p:Platform=x64

    - name: Upload Compiled Artifacts
      uses: actions/upload-artifact@v4.4.3
      with:
        # ${{ github.ref_name }} 会自动变成当前分支名（如 3.6.x_plus 或 master）
        name: UACME-x64-${{ github.ref_name }}
        path: |
          Source/bin/**
          Source/**/Release/*.exe
          Source/**/Release/*.dll
        if-no-files-found: warn
